### ISSUE TITLE
Opens tsconfig

### ISSUE THREAD

**Issue by dudewad** [pkelleter/angular-cli-quick-switch-plugin#10] opened 2018-07-23 00:19 UTC
First off, great plugin, very cool. It's convenient to be able to switch files like this.

However I have an issue where `tsconfig.json` is opened every time I try to do a switch.

Repro is pretty simple... open a file, hit `alt+s`, the file switches, but tsconfig.json opens along with it without fail every time.

This is annoying enough that I won't actually use the plugin :(

FWIW, I'm using `Intellij IDEA Ultimate 2018.1`, not Webstorm.

**Comment by pkelleter** [comment] 2018-08-18 07:31
Unfortunately i can not reproduce this bug - and it doesn't make sense to me just by looking at the code either. Since I do not have a copy of Ultimate I just can test it in the versions i have (PHPStorm, WebStorm, Community) - which all work fine.

Can you try to provide some more information?

What happens if you delete the tsconfig.json for test purposes. Does it open another file then?
What happens if you import the project from scratch? Does it keep happening?

Thank you for your input

**Comment by pkelleter** [comment] 2018-10-26 20:00
since i still can not reproduce this bug - and nobody else reported this behavior, i will close this issue for now

**Closed as completed by pkelleter** 2018-10-26 20:00 UTC
